schema_version = "1.0.0"

id = "votv_print_exporter"
version = "1.2.0"
name = "VOTV Print Exporter"
tagline = "An extension to export 3D models as printable objects in VOTV"
maintainer = "drywallEater (doctorkrazy)"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
# tags = ["Export"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

# Untested, will remain off
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]

files = "Export OBJ/PNG to disk"